name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Prepare virtual env'
        run: python3 -m venv qilimanjaro_venv && source qilimanjaro_venv/bin/activate
      - name: 'Install requirements'
        run: pip3 install -r requirements.txt
      - name: 'Check code style'
        run: black --check --diff .
      - name: 'Run linter'
        run: flake8 --count --statistics --show-source .
      - name: 'Run webserver'
        run: python3 restful_api.py
      - name: 'Run unit tests'
        run: |
          sleep 10 &&
          python3 unit_tests.py
